#!/bin/bash

# Slightly modified to allow runtime checking for webhook in a Nix package
# https://github.com/tdharris/os-mdadm-alert-webhook/commit/4e464b1d5980aa9afd99215c9a24411ded36d132

# mdadm Discord Webhook Notification Script
# Author: Generated by GitHub Copilot
# Purpose: Send mdadm events to Discord as formatted notifications
# Usage: mdadm-discord-webhook.sh <event> <device> [component]

set -euo pipefail

# ==============================================================================
# CONFIGURATION - EDIT THIS SECTION
# ==============================================================================

# Discord webhook URL - REPLACE WITH YOUR ACTUAL WEBHOOK URL
# Get this from: Discord Server Settings → Integrations → Webhooks → New Webhook
# ADDED BY NIX PACKAGE
# DISCORD_WEBHOOK_URL=""

# Notification level configuration
# NOTIFY_LEVEL options:
#   "all"      - Notify for all events (including routine array checks)
#   "critical" - Only critical events (failures, degraded arrays, actual rebuilds - excludes routine checks)
NOTIFY_LEVEL="critical"

# Array check notification settings
# Set to "true" to receive notifications for routine array checks/scrubs
# Set to "false" to suppress check notifications (recommended for most users)
NOTIFY_ARRAY_CHECKS="false"

# ==============================================================================
# END CONFIGURATION
# =============================================================================="

# Color constants for Discord embed colors
readonly COLOR_INFO=3447003      # Blue
readonly COLOR_SUCCESS=3066993   # Green
readonly COLOR_WARNING=15105570  # Orange
readonly COLOR_ERROR=15158332    # Red

# Script metadata
readonly SCRIPT_NAME="mdadm-discord-webhook"
readonly VERSION="1.0.0"

# Function to display usage information
usage() {
    cat << EOF
Usage: $0 <event> <device> [component]

Arguments:
    event                  mdadm event type (e.g., Fail, TestMessage, etc.)
    device                 MD device name (e.g., /dev/md0)
    component              Optional component device (e.g., /dev/sda1)

Examples:
    $0 "Fail" "/dev/md0" "/dev/sda1"
    $0 "TestMessage" "/dev/md0"

Configuration:
    Edit the configuration variables at the top of this script:
    
    DISCORD_WEBHOOK_URL    - Your Discord webhook URL (required)
    NOTIFY_LEVEL           - Notification level: "all" or "critical"
    NOTIFY_ARRAY_CHECKS    - Set to "true" to get routine array check notifications (only applies when NOTIFY_LEVEL="all")

    Notification Levels:
    • "all"                - All events (including routine array checks)
    • "critical"           - Only important events (failures, degraded arrays, actual rebuilds - excludes routine checks)

This script is designed to be used with mdadm's PROGRAM configuration option
in /etc/mdadm.conf or /etc/mdadm/mdadm.conf:

    PROGRAM $0

Version: $VERSION
EOF
}

# Function to log messages
log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [$SCRIPT_NAME] $*" >&2
}

# Function to get color based on event type
get_event_color() {
    local event="$1"
    local device="$2"
    local is_check="false"
    
    # Check if this is an array check for rebuild events
    if [[ "$event" =~ ^Rebuild ]]; then
        if is_array_check "$device" "$event"; then
            is_check="true"
        fi
    fi
    
    case "$event" in
        "Fail"|"FailSpare"|"DegradedArray"|"SparesMissing")
            echo "$COLOR_ERROR"
            ;;
        "RebuildStarted"|"RebuildNN"|"RebuildFinished")
            if [[ "$is_check" == "true" ]]; then
                echo "$COLOR_INFO"  # Blue for routine checks
            else
                echo "$COLOR_WARNING"  # Orange for actual rebuilds
            fi
            ;;
        "TestMessage"|"NewArray"|"SpareActive")
            echo "$COLOR_SUCCESS"
            ;;
        "DeviceDisappeared"|"MoveSpare")
            echo "$COLOR_WARNING"
            ;;
        *)
            echo "$COLOR_INFO"
            ;;
    esac
}

# Function to get event description
get_event_description() {
    local event="$1"
    local device="$2"
    local is_check="false"
    
    # Check if this is an array check for rebuild events
    if [[ "$event" =~ ^Rebuild ]]; then
        if is_array_check "$device" "$event"; then
            is_check="true"
        fi
    fi
    
    case "$event" in
        "Fail")
            echo "A device in the array has failed"
            ;;
        "FailSpare")
            echo "A spare device has failed"
            ;;
        "DegradedArray")
            echo "The array has become degraded"
            ;;
        "SparesMissing")
            echo "The array is missing spare devices"
            ;;
        "RebuildStarted")
            if [[ "$is_check" == "true" ]]; then
                echo "Routine array check/scrub has started"
            else
                echo "Array rebuild has started"
            fi
            ;;
        "RebuildNN")
            if [[ "$is_check" == "true" ]]; then
                echo "Routine array check/scrub is in progress"
            else
                echo "Array rebuild is in progress"
            fi
            ;;
        "RebuildFinished")
            if [[ "$is_check" == "true" ]]; then
                echo "Routine array check/scrub has completed"
            else
                echo "Array rebuild has finished"
            fi
            ;;
        "TestMessage")
            echo "Test message from mdadm"
            ;;
        "NewArray")
            echo "A new array has been created"
            ;;
        "SpareActive")
            echo "A spare device has become active"
            ;;
        "DeviceDisappeared")
            echo "A device has disappeared from the system"
            ;;
        "MoveSpare")
            echo "A spare device has been moved between arrays"
            ;;
        *)
            echo "Unknown event type: $event"
            ;;
    esac
}

# Function to detect if this is an array check vs actual rebuild
is_array_check() {
    local device="$1"
    local event="$2"
    
    # Only check for rebuild-related events
    if [[ ! "$event" =~ ^Rebuild ]]; then
        return 1  # Not a rebuild event
    fi
    
    # Check if device exists and get its state
    if [[ -e "$device" ]]; then
        local array_info
        if array_info=$(mdadm --detail "$device" 2>/dev/null); then
            local state
            state=$(echo "$array_info" | grep -i "State :" | cut -d: -f2- | xargs)
            
            # Array check indicators:
            # - State contains "checking" 
            # - State is "clean" with checking/resync activity
            if [[ "$state" =~ checking ]] || [[ "$state" == "clean, checking" ]]; then
                return 0  # This is an array check
            fi
            
            # Additional check: look for "Check Status" line which appears during checks
            if echo "$array_info" | grep -qi "Check Status"; then
                return 0  # This is an array check
            fi
        fi
    fi
    
    return 1  # Assume actual rebuild if we can't determine
}

# Function to determine if event should be notified based on configuration
should_notify() {
    local event="$1"
    local device="$2"
    local is_check="$3"
    
    case "$NOTIFY_LEVEL" in
        "all")
            # All events - but check if user wants to suppress array checks
            if [[ "$event" =~ ^Rebuild ]] && [[ "$is_check" == "true" ]] && [[ "$NOTIFY_ARRAY_CHECKS" == "false" ]]; then
                return 1  # Suppress array checks if user doesn't want them
            fi
            return 0  # Notify everything else
            ;;
        "critical")
            # Critical events only (excludes routine checks)
            case "$event" in
                "Fail"|"FailSpare"|"DegradedArray"|"SparesMissing"|"DeviceDisappeared"|"SpareActive"|"NewArray")
                    return 0
                    ;;
                "Rebuild"*)
                    # For rebuild events, only notify if it's an actual rebuild (not routine check)
                    if [[ "$is_check" == "true" ]]; then
                        return 1  # Suppress routine array checks
                    else
                        return 0  # Allow actual rebuilds
                    fi
                    ;;
                "TestMessage")
                    return 0  # Always allow test messages
                    ;;
                *)
                    return 1  # Suppress other events
                    ;;
            esac
            ;;
        *)
            log "Warning: Unknown NOTIFY_LEVEL '$NOTIFY_LEVEL', defaulting to 'all'"
            return 0
            ;;
    esac
}

# Function to get hostname
get_hostname() {
    hostname -f 2>/dev/null || hostname 2>/dev/null || echo "unknown"
}

# Function to get system information
get_system_info() {
    local device="$1"
    local event="$2"
    local info=""
    
    # Get array status if device exists
    if [[ -e "$device" ]]; then
        local array_info
        if array_info=$(mdadm --detail "$device" 2>/dev/null); then
            local state level devices
            state=$(echo "$array_info" | grep -i "State :" | cut -d: -f2- | xargs)
            level=$(echo "$array_info" | grep -i "Raid Level :" | cut -d: -f2- | xargs)
            devices=$(echo "$array_info" | grep -i "Total Devices :" | cut -d: -f2- | xargs)
            failed=$(echo "$array_info" | grep -i "Failed Devices :" | cut -d: -f2- | xargs)
            
            info="**Array State:** $state\\n"
            info+="**RAID Level:** $level\\n"
            info+="**Total Devices:** $devices\\n"
            info+="**Failed Devices:** $failed\\n"
            
            # Add check/rebuild specific information
            if [[ "$event" =~ ^Rebuild ]]; then
                # Look for rebuild/check progress information
                local progress_info
                progress_info=$(echo "$array_info" | grep -E "(Rebuild Status|Check Status|Resync Status)" | head -1)
                if [[ -n "$progress_info" ]]; then
                    local progress_line
                    progress_line=$(echo "$progress_info" | cut -d: -f2- | xargs)
                    
                    if is_array_check "$device" "$event"; then
                        info+="**Check Progress:** $progress_line\\n"
                    else
                        info+="**Rebuild Progress:** $progress_line\\n"
                    fi
                fi
                
                # Add estimated completion time if available
                local finish_info
                finish_info=$(echo "$array_info" | grep -i "finish=" | sed 's/.*finish=//' | sed 's/speed=.*//' | xargs)
                if [[ -n "$finish_info" ]]; then
                    info+="**Estimated Completion:** $finish_info\\n"
                fi
            fi
        fi
    fi
    
    # Add system load and uptime
    if command -v uptime >/dev/null 2>&1; then
        local uptime_info
        uptime_info=$(uptime | sed 's/.*up //' | sed 's/, *[0-9]* users.*//')
        info+="**System Uptime:** $uptime_info\\n"
    fi
    
    echo "$info"
}

# Function to send Discord webhook
send_discord_webhook() {
    local event="$1"
    local device="$2"
    local component="$3"
    
    local hostname
    local timestamp
    local color
    local description
    local system_info
    
    hostname=$(get_hostname)
    timestamp=$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")
    color=$(get_event_color "$event" "$device")
    description=$(get_event_description "$event" "$device")
    system_info=$(get_system_info "$device" "$event")
    
    # Build the JSON payload
    local json_payload
    json_payload=$(cat << EOF
{
    "embeds": [
        {
            "title": "mdadm Event: $event",
            "description": "$description",
            "color": $color,
            "timestamp": "$timestamp",
            "fields": [
                {
                    "name": "Device",
                    "value": "\`$device\`",
                    "inline": true
                },
                {
                    "name": "Host",
                    "value": "$hostname",
                    "inline": true
                }$(if [[ -n "$component" ]]; then
                    echo ","
                    cat << COMPONENT_EOF
                {
                    "name": "Component",
                    "value": "\`$component\`",
                    "inline": true
                }
COMPONENT_EOF
                fi)$(if [[ -n "$system_info" ]]; then
                    echo ","
                    cat << INFO_EOF
                {
                    "name": "System Information",
                    "value": "$system_info",
                    "inline": false
                }
INFO_EOF
                fi)
            ],
            "footer": {
                "text": "mdadm-discord-webhook v$VERSION"
            }
        }
    ]
}
EOF
)

    log "Sending Discord notification for event: $event, device: $device"
    
    # Send the webhook using curl
    if curl -H "Content-Type: application/json" \
            -d "$json_payload" \
            -X POST \
            --max-time 30 \
            --retry 3 \
            --retry-delay 2 \
            --silent \
            --show-error \
            "$DISCORD_WEBHOOK_URL"; then
        log "Successfully sent Discord notification"
        return 0
    else
        log "Failed to send Discord notification"
        return 1
    fi
}

# Main function
main() {
    # Check if help is requested
    if [[ $# -eq 0 ]] || [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]; then
        usage
        exit 0
    fi
    
    # Validate number of arguments
    if [[ $# -lt 2 ]] || [[ $# -gt 3 ]]; then
        echo "Error: Invalid number of arguments" >&2
        usage >&2
        exit 1
    fi
    
    local event="$1"
    local device="$2"
    local component="${3:-}"
    
    # Validate webhook URL configuration
    if [[ "$DISCORD_WEBHOOK_URL" == "https://discord.com/api/webhooks/YOUR_WEBHOOK_ID/YOUR_WEBHOOK_TOKEN" ]]; then
        log "Error: Please configure DISCORD_WEBHOOK_URL in the script before use"
        log "Edit the DISCORD_WEBHOOK_URL variable at the top of this script"
        exit 1
    fi
    
    if [[ ! "$DISCORD_WEBHOOK_URL" =~ ^https://discord\.com/api/webhooks/ ]] && [[ ! "$DISCORD_WEBHOOK_URL" =~ ^https://discordapp\.com/api/webhooks/ ]]; then
        log "Warning: Webhook URL doesn't appear to be a valid Discord webhook URL"
    fi
    
    # Check if required tools are available
    if ! command -v curl >/dev/null 2>&1; then
        log "Error: curl is required but not installed"
        exit 1
    fi
    
    if ! command -v mdadm >/dev/null 2>&1; then
        log "Warning: mdadm command not found, system information will be limited"
    fi
    
    # Check if this event should be notified based on configuration
    local is_check="false"
    if is_array_check "$device" "$event"; then
        is_check="true"
    fi
    
    if ! should_notify "$event" "$device" "$is_check"; then
        log "Event '$event' suppressed by notification level '$NOTIFY_LEVEL' (is_check=$is_check)"
        exit 0
    fi
    
    # Send the notification
    if send_discord_webhook "$event" "$device" "$component"; then
        log "Notification sent successfully"
        exit 0
    else
        log "Failed to send notification"
        exit 1
    fi
}

# Run main function with all arguments
main "$@"

