#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

sh ~/.config/autostart/resolution.sh
sh ~/.config/polybar/launch.sh
feh --bg-fill ~/Pictures/backgrounds/Catppuccin/unicat.png
picom -b

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.50

bspc config normal_border_color "#454545"
bspc config focused_border_color "#F5C2E7"

bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
